use std::env;
use std::fs::{self, File};
use std::io::{BufReader, Read};
use std::path::Path;
use std::collections::HashMap;
use std::time::Instant;

use fastq::{Parser, Record};
use csv::Reader;
use flate2::read::MultiGzDecoder;
use flate2::write::GzEncoder;
use flate2::Compression;

use charming::{Chart, ImageRenderer, ImageFormat};
use charming::element::{NameLocation, AxisType, TextStyle, TextAlign};
use charming::component::{Axis, Title};
use charming::series::Bar;

struct SequenceInfo {
    name: String,
    sequence: String,
    count: usize,
}

fn main() {
    let args: Vec<String> = env::args().collect();

    // Check for the optional --dump flag
    let dump_matched = args.iter().any(|a| a == "--dump");

    // Build positional args by filtering out --dump
    let positional_args: Vec<&String> = args.iter().filter(|a| *a != "--dump").collect();

    if positional_args.len() < 4 {
        eprintln!("Usage: {} [--dump] <mode: 'seq' or 'csv'> <sequence or path_to_sequences.csv> <fastq_directory> [mismatch_percentage]", args[0]);
        return;
    }
    let mode = positional_args[1];
    let sequences_input = positional_args[2];
    let fastq_directory = positional_args[3];
    let mismatch_percentage: f64 = if positional_args.len() > 4 {
        positional_args[4].parse().expect("Invalid mismatch percentage")
    } else {
        0.0 // Default value if the argument is not provided
    };

    let mut sequences = HashMap::new();
    let mut sequence_order: Vec<String> = Vec::new();

    match mode.as_str() {
        "--seq" => {
            // Directly use the provided sequence
            let name = "Query".to_string();
            let sequence = sequences_input.to_uppercase();
            sequences.insert(name.clone(), SequenceInfo { name, sequence, count: 0 });
            sequence_order.push("Query".to_string());
        },
        "--csv" => {
            // Read sequences from the CSV file
            let mut rdr = Reader::from_path(sequences_input).expect("Failed to read CSV file");
            for result in rdr.records() {
                let record = result.expect("Error reading CSV record");
                let name = record[0].to_string();
                let sequence = record[1].to_uppercase();
                sequences.insert(name.clone(), SequenceInfo { name: name.clone(), sequence, count: 0 });
                sequence_order.push(name);
            }
        },
        _ => {
            eprintln!("Invalid mode. Use '--seq' for direct sequence input or '--csv' for CSV file input.");
            return;
        }
    }
    // Process each FASTQ file in the directory
    let paths: Vec<_> = fs::read_dir(fastq_directory)
        .expect("Failed to read directory")
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .collect();
    for path in paths {
        let file_name = path.file_name().and_then(std::ffi::OsStr::to_str).unwrap_or_default();

        // Skip output files generated by a previous --dump run
        if file_name.ends_with(".matched.fastq.gz") {
            continue;
        }

        let file_ext = path.extension().and_then(std::ffi::OsStr::to_str).unwrap_or_default();

        if file_ext == "fastq" || file_ext == "fq" {
            process_fastq_file(&path, &mut sequences, mismatch_percentage, &sequence_order, dump_matched);
        } else if file_ext == "gz" {
            if let Some(stem) = path.file_stem().and_then(std::ffi::OsStr::to_str) {
                if stem.ends_with(".fastq") || stem.ends_with(".fq") {
                    process_fastq_file(&path, &mut sequences, mismatch_percentage, &sequence_order, dump_matched);
                }
            }
        }
    }
}

fn process_fastq_file(path: &Path, sequences: &mut HashMap<String, SequenceInfo>, mismatch_percentage: f64, sequence_order: &[String], dump_matched: bool) {
    let start = Instant::now();

    let file = File::open(path).expect("Failed to open FASTQ file");
    let file_ext = path.extension().and_then(std::ffi::OsStr::to_str).unwrap_or_default();
    
    let box_reader: Box<dyn Read> = if file_ext == "gz" {
        Box::new(BufReader::new(MultiGzDecoder::new(file)))
    } else {
        Box::new(BufReader::new(file))
    };

    // Set up the gzip output writer for matched reads if --dump was requested
    let mut gz_writer: Option<GzEncoder<File>> = if dump_matched {
        let file_name = path.file_name().unwrap().to_str().unwrap();
        let new_name = format!("{}.matched.fastq.gz", file_name);
        let out_path = path.parent().unwrap_or_else(|| Path::new(".")).join(new_name);
        let out_file = File::create(out_path).expect("Failed to create output file");
        Some(GzEncoder::new(out_file, Compression::default()))
    } else {
        None
    };

    let parser = Parser::new(box_reader);
    let mut total_reads = 0;

    let result = parser.each(|record| {
        total_reads += 1;
        let read = String::from_utf8_lossy(record.seq()).to_uppercase();
        let mut matched = false;

        for seq_info in sequences.values_mut() {
            if is_match(&read, &seq_info.sequence, mismatch_percentage) {
                seq_info.count += 1;
                matched = true;
            }
        }

        if matched {
            if let Some(ref mut encoder) = gz_writer {
                record.write(encoder).expect("Failed to write matched record to output file");
            }
        }

        true
    });

    // Finish the gzip stream to flush and write the footer
    if let Some(encoder) = gz_writer {
        encoder.finish().expect("Failed to finish Gzip stream");
    }

    if let Err(e) = result {
        eprintln!("Error processing FASTQ file: {}", e);
        return;
    }
    println!("-----------------------------------\n");
    println!("Results for file: {:?}", path.file_name().unwrap());
    println!("Total reads: {}, Mismatch allowance: {:.2} \n", total_reads, mismatch_percentage);
    println!("Name, Sequence, Count, Percentage");
    for name in sequence_order.iter() {
        if let Some(seq_info) = sequences.get(name) {
            let percentage = (seq_info.count as f64 / total_reads as f64) * 100.0;
            println!("{},{},{},{:.2}%", seq_info.name, seq_info.sequence, seq_info.count, percentage);
        }
    }

    let duration = start.elapsed();
    println!("\nTime taken for {:?}: {:?}\n", path.file_name().unwrap(), duration);

    // Create a chart of the results
    let sequence_names: Vec<String> = sequences.keys().cloned().collect();
    let percentages: Vec<f64> = sequences.values()
        .map(|seq_info| (seq_info.count as f64 / total_reads as f64) * 100.0)
        .collect();

        let file_path = match path.to_str() {
            Some(str_path) => format!("{}.png", str_path),
            None => panic!("Invalid file path"),
        };

    chart(sequence_names, percentages, &file_path, &mismatch_percentage);

        
        // Reset the counts for sequences after processing each file
        for seq_info in sequences.values_mut() {
            seq_info.count = 0;
    }
}

fn is_match(read: &str, sequence: &str, mismatch_percentage: f64) -> bool {
    let mismatches_allowed = (sequence.len() as f64 * mismatch_percentage).round() as usize;
    let sequence_len = sequence.len();

    // Iterate over all possible alignments of the sequence within the read
    for start in 0..=read.len().saturating_sub(sequence_len) {
        let mut mismatches = 0;

        for (read_char, sequence_char) in read[start..].chars().zip(sequence.chars()) {
            if read_char != sequence_char {
                mismatches += 1;
                if mismatches > mismatches_allowed {
                    break;
                }
            }
        }

        // Return true as soon as a match is found
        if mismatches <= mismatches_allowed {
            return true;
        }
    }

    false
}

pub fn chart(sequence_names: Vec<String>, percentages: Vec<f64>, file_path: &str, mismatch_percentage: &f64) {
    println!("{:?} {:?} {}", sequence_names, percentages, file_path);
    let chart = Chart::new()
        .title(
            Title::new()
                .text(file_path.get(2..).unwrap().strip_suffix(".png").unwrap())
                .text_style(TextStyle::new().font_size(28).color("#000000"))
                .text_align(TextAlign::Auto)
                .item_gap(-1)
                .subtext("mismatch allowance: ".to_owned() + &mismatch_percentage.to_string())
                .subtext_style(TextStyle::new().font_size(16).color("#000000"))
            )
        .x_axis(
            Axis::new()
                .type_(AxisType::Category)
                .data(sequence_names)
                .name("sequence name")
                .name_gap(50)
                .name_location(NameLocation::Center)

            )
        .y_axis(
            Axis::new()
                .type_(AxisType::Value)
                .min(0.0)
                .max(100.0)
                .name_gap(50)
                .name("match percentage (%)")
                .name_location(NameLocation::Center)
            )
        .series(Bar::new().data(percentages))
        .background_color("#ffffff"
    );

    let mut renderer = ImageRenderer::new(800, 600);
    renderer.save_format(ImageFormat::Png, &chart, file_path).err();
    }